import type { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import styles from "../../styles/Home.module.scss";
import Tab from "../../components/Tab";
import PostTabListItem from "../../components/PostTabListItem";

const Board: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Bi-Connect</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Tab
				tabs={{
					Posts: {
						data: [
							{
								postName: "Hi",
								postContent: "What's up?",
							},
							{
								postName: "Hi",
								postContent: "What's up?",
							},
						],
						renderComponent: PostTabListItem,
						createButtonOnClick: () => {
							console.log("creating board");
						},
					},
				}}
			/>
		</div>
	);
};

export default Board;
