import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import styles from "../../styles/Home.module.scss";
import MyButton from "../../components/myButton";
import Tab from "../../components/Tab";
import UserTabListItem from "../../components/UserTabListItem";
import BoardTabListItem from "../../components/BoardTabListItem";

const Home: NextPage = () => {
	const [email, setEmail] = useState("");
	const [password, setPassword] = useState("");

	const handleEmailInputOnChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		let input: string = e.target.value;
		setEmail(input);
	};

	const handlePasswordInputOnChange = (
		e: React.ChangeEvent<HTMLInputElement>
	) => {
		let input: string = e.target.value;
		setPassword(input);
	};

	const handleSubmit = (e: React.MouseEvent<HTMLButtonElement>) => {
		console.log(email);
		console.log(password);
		//TODO
		//API call
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Bi-Connect</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Tab
				tabs={{
					Users: {
						data: [
							{ username: "ichang1", email: "ichang1@haverford.edu" },
							{ username: "jhan1", email: "jhan1@brynmawr.edu" },
						],
						renderComponent: UserTabListItem,
						createButtonOnClick: () => {
							console.log("creating user");
						},
					},
					Boards: {
						data: [
							{
								boardname: "Bi-Co Confession",
								boardDescription: "This is a page for confessions.",
							},
							{
								boardname: "Bi-Co Badminton",
								boardDescription: "This is a page for badminton club.",
							},
						],
						renderComponent: BoardTabListItem,
						createButtonOnClick: () => {
							console.log("creating board");
						},
					},
				}}
			/>
		</div>
	);
};

export default Home;
