// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package edu.brynmawr.cmsc353.webapp;

import com.apollographql.apollo.api.Input;
import com.apollographql.apollo.api.InputType;
import com.apollographql.apollo.api.internal.InputFieldMarshaller;
import com.apollographql.apollo.api.internal.InputFieldWriter;
import com.apollographql.apollo.api.internal.Utils;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;

public final class BoardIdInput implements InputType {
  private final Input<String> _id;

  private final @NotNull String name;

  private transient volatile int $hashCode;

  private transient volatile boolean $hashCodeMemoized;

  BoardIdInput(Input<String> _id, @NotNull String name) {
    this._id = _id;
    this.name = name;
  }

  public @Nullable String _id() {
    return this._id.value;
  }

  public @NotNull String name() {
    return this.name;
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public InputFieldMarshaller marshaller() {
    return new InputFieldMarshaller() {
      @Override
      public void marshal(InputFieldWriter writer) throws IOException {
        if (_id.defined) {
          writer.writeString("_id", _id.value);
        }
        writer.writeString("name", name);
      }
    };
  }

  @Override
  public int hashCode() {
    if (!$hashCodeMemoized) {
      int h = 1;
      h *= 1000003;
      h ^= _id.hashCode();
      h *= 1000003;
      h ^= name.hashCode();
      $hashCode = h;
      $hashCodeMemoized = true;
    }
    return $hashCode;
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof BoardIdInput) {
      BoardIdInput that = (BoardIdInput) o;
      return this._id.equals(that._id)
       && this.name.equals(that.name);
    }
    return false;
  }

  public static final class Builder {
    private Input<String> _id = Input.absent();

    private @NotNull String name;

    Builder() {
    }

    public Builder _id(@Nullable String _id) {
      this._id = Input.fromNullable(_id);
      return this;
    }

    public Builder name(@NotNull String name) {
      this.name = name;
      return this;
    }

    public Builder _idInput(@NotNull Input<String> _id) {
      this._id = Utils.checkNotNull(_id, "_id == null");
      return this;
    }

    public BoardIdInput build() {
      Utils.checkNotNull(name, "name == null");
      return new BoardIdInput(_id, name);
    }
  }
}
