// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package edu.brynmawr.cmsc353.webapp;

import com.apollographql.apollo.api.Input;
import com.apollographql.apollo.api.InputType;
import com.apollographql.apollo.api.internal.InputFieldMarshaller;
import com.apollographql.apollo.api.internal.InputFieldWriter;
import com.apollographql.apollo.api.internal.Utils;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;

public final class CreateCommentInput implements InputType {
  private final @NotNull String content;

  private final Input<String> parentId;

  private transient volatile int $hashCode;

  private transient volatile boolean $hashCodeMemoized;

  CreateCommentInput(@NotNull String content, Input<String> parentId) {
    this.content = content;
    this.parentId = parentId;
  }

  public @NotNull String content() {
    return this.content;
  }

  public @Nullable String parentId() {
    return this.parentId.value;
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public InputFieldMarshaller marshaller() {
    return new InputFieldMarshaller() {
      @Override
      public void marshal(InputFieldWriter writer) throws IOException {
        writer.writeString("content", content);
        if (parentId.defined) {
          writer.writeString("parentId", parentId.value);
        }
      }
    };
  }

  @Override
  public int hashCode() {
    if (!$hashCodeMemoized) {
      int h = 1;
      h *= 1000003;
      h ^= content.hashCode();
      h *= 1000003;
      h ^= parentId.hashCode();
      $hashCode = h;
      $hashCodeMemoized = true;
    }
    return $hashCode;
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof CreateCommentInput) {
      CreateCommentInput that = (CreateCommentInput) o;
      return this.content.equals(that.content)
       && this.parentId.equals(that.parentId);
    }
    return false;
  }

  public static final class Builder {
    private @NotNull String content;

    private Input<String> parentId = Input.absent();

    Builder() {
    }

    public Builder content(@NotNull String content) {
      this.content = content;
      return this;
    }

    public Builder parentId(@Nullable String parentId) {
      this.parentId = Input.fromNullable(parentId);
      return this;
    }

    public Builder parentIdInput(@NotNull Input<String> parentId) {
      this.parentId = Utils.checkNotNull(parentId, "parentId == null");
      return this;
    }

    public CreateCommentInput build() {
      Utils.checkNotNull(content, "content == null");
      return new CreateCommentInput(content, parentId);
    }
  }
}
