package edu.brynmawr.cmsc353.webapp;// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//

import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Query;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ScalarTypeAdapters;
import com.apollographql.apollo.api.internal.InputFieldMarshaller;
import com.apollographql.apollo.api.internal.InputFieldWriter;
import com.apollographql.apollo.api.internal.OperationRequestBodyComposer;
import com.apollographql.apollo.api.internal.QueryDocumentMinifier;
import com.apollographql.apollo.api.internal.ResponseFieldMapper;
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller;
import com.apollographql.apollo.api.internal.ResponseReader;
import com.apollographql.apollo.api.internal.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.UnmodifiableMapBuilder;
import com.apollographql.apollo.api.internal.Utils;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import okio.Buffer;
import okio.BufferedSource;
import okio.ByteString;
import type.CustomType;

public final class GetPostCommentsQuery implements Query<GetPostCommentsQuery.Data, GetPostCommentsQuery.Data, GetPostCommentsQuery.Variables> {
  public static final String OPERATION_ID = "363bcf98eb6d4617e725d061ae06fdb595dddf6d6230f19c1cbfb0740b3163e7";

  public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
    "query getPostComments($input: PostIdInput!) {\n"
        + "  getPostComments(input: $input) {\n"
        + "    __typename\n"
        + "    _id\n"
        + "    createdAt\n"
        + "    creatorName\n"
        + "    content\n"
        + "    likes\n"
        + "    dislikes\n"
        + "    parentId\n"
        + "    postId\n"
        + "  }\n"
        + "}"
  );

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "getPostComments";
    }
  };

  private final Variables variables;

  public GetPostCommentsQuery(@NotNull PostIdInput input) {
    Utils.checkNotNull(input, "input == null");
    variables = new Variables(input);
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public Data wrapData(Data data) {
    return data;
  }

  @Override
  public Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  @Override
  @NotNull
  public Response<Data> parse(@NotNull final BufferedSource source,
                              @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
    return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
  }

  @Override
  @NotNull
  public Response<Data> parse(@NotNull final ByteString byteString,
                              @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
    return parse(new Buffer().write(byteString), scalarTypeAdapters);
  }

  @Override
  @NotNull
  public Response<Data> parse(@NotNull final BufferedSource source) throws
      IOException {
    return parse(source, ScalarTypeAdapters.DEFAULT);
  }

  @Override
  @NotNull
  public Response<Data> parse(@NotNull final ByteString byteString) throws
      IOException {
    return parse(byteString, ScalarTypeAdapters.DEFAULT);
  }

  @Override
  @NotNull
  public ByteString composeRequestBody(@NotNull final ScalarTypeAdapters scalarTypeAdapters) {
    return OperationRequestBodyComposer.compose(this, false, true, scalarTypeAdapters);
  }

  @NotNull
  @Override
  public ByteString composeRequestBody() {
    return OperationRequestBodyComposer.compose(this, false, true, ScalarTypeAdapters.DEFAULT);
  }

  @Override
  @NotNull
  public ByteString composeRequestBody(final boolean autoPersistQueries,
      final boolean withQueryDocument, @NotNull final ScalarTypeAdapters scalarTypeAdapters) {
    return OperationRequestBodyComposer.compose(this, autoPersistQueries, withQueryDocument, scalarTypeAdapters);
  }

  public static final class Builder {
    private @NotNull PostIdInput input;

    Builder() {
    }

    public Builder input(@NotNull PostIdInput input) {
      this.input = input;
      return this;
    }

    public GetPostCommentsQuery build() {
      Utils.checkNotNull(input, "input == null");
      return new GetPostCommentsQuery(input);
    }
  }

  public static final class Variables extends Operation.Variables {
    private final @NotNull PostIdInput input;

    private final transient Map<String, Object> valueMap = new LinkedHashMap<>();

    Variables(@NotNull PostIdInput input) {
      this.input = input;
      this.valueMap.put("input", input);
    }

    public @NotNull PostIdInput input() {
      return input;
    }

    @Override
    public Map<String, Object> valueMap() {
      return Collections.unmodifiableMap(valueMap);
    }

    @Override
    public InputFieldMarshaller marshaller() {
      return new InputFieldMarshaller() {
        @Override
        public void marshal(InputFieldWriter writer) throws IOException {
          writer.writeObject("input", input.marshaller());
        }
      };
    }
  }

  /**
   * Data from the response after executing this GraphQL operation
   */
  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forList("getPostComments", "getPostComments", new UnmodifiableMapBuilder<String, Object>(1)
      .put("input", new UnmodifiableMapBuilder<String, Object>(2)
        .put("kind", "Variable")
        .put("variableName", "input")
        .build())
      .build(), false, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull List<GetPostComment> getPostComments;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@NotNull List<GetPostComment> getPostComments) {
      this.getPostComments = Utils.checkNotNull(getPostComments, "getPostComments == null");
    }

    public @NotNull List<GetPostComment> getPostComments() {
      return this.getPostComments;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeList($responseFields[0], getPostComments, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              for (Object item : items) {
                listItemWriter.writeObject(((GetPostComment) item).marshaller());
              }
            }
          });
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "getPostComments=" + getPostComments
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return this.getPostComments.equals(that.getPostComments);
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= getPostComments.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final GetPostComment.Mapper getPostCommentFieldMapper = new GetPostComment.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final List<GetPostComment> getPostComments = reader.readList($responseFields[0], new ResponseReader.ListReader<GetPostComment>() {
          @Override
          public GetPostComment read(ResponseReader.ListItemReader listItemReader) {
            return listItemReader.readObject(new ResponseReader.ObjectReader<GetPostComment>() {
              @Override
              public GetPostComment read(ResponseReader reader) {
                return getPostCommentFieldMapper.map(reader);
              }
            });
          }
        });
        return new Data(getPostComments);
      }
    }
  }

  public static class GetPostComment {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("_id", "_id", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forCustomType("createdAt", "createdAt", null, false, CustomType.DATETIME, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("creatorName", "creatorName", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("content", "content", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forInt("likes", "likes", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forInt("dislikes", "dislikes", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("parentId", "parentId", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forString("postId", "postId", null, false, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @NotNull String _id;

    final @NotNull Object createdAt;

    final @NotNull String creatorName;

    final @NotNull String content;

    final int likes;

    final int dislikes;

    final @Nullable String parentId;

    final @NotNull String postId;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public GetPostComment(@NotNull String __typename, @NotNull String _id,
        @NotNull Object createdAt, @NotNull String creatorName, @NotNull String content, int likes,
        int dislikes, @Nullable String parentId, @NotNull String postId) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this._id = Utils.checkNotNull(_id, "_id == null");
      this.createdAt = Utils.checkNotNull(createdAt, "createdAt == null");
      this.creatorName = Utils.checkNotNull(creatorName, "creatorName == null");
      this.content = Utils.checkNotNull(content, "content == null");
      this.likes = likes;
      this.dislikes = dislikes;
      this.parentId = parentId;
      this.postId = Utils.checkNotNull(postId, "postId == null");
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @NotNull String _id() {
      return this._id;
    }

    public @NotNull Object createdAt() {
      return this.createdAt;
    }

    public @NotNull String creatorName() {
      return this.creatorName;
    }

    public @NotNull String content() {
      return this.content;
    }

    public int likes() {
      return this.likes;
    }

    public int dislikes() {
      return this.dislikes;
    }

    public @Nullable String parentId() {
      return this.parentId;
    }

    public @NotNull String postId() {
      return this.postId;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeString($responseFields[1], _id);
          writer.writeCustom((ResponseField.CustomTypeField) $responseFields[2], createdAt);
          writer.writeString($responseFields[3], creatorName);
          writer.writeString($responseFields[4], content);
          writer.writeInt($responseFields[5], likes);
          writer.writeInt($responseFields[6], dislikes);
          writer.writeString($responseFields[7], parentId);
          writer.writeString($responseFields[8], postId);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "GetPostComment{"
          + "__typename=" + __typename + ", "
          + "_id=" + _id + ", "
          + "createdAt=" + createdAt + ", "
          + "creatorName=" + creatorName + ", "
          + "content=" + content + ", "
          + "likes=" + likes + ", "
          + "dislikes=" + dislikes + ", "
          + "parentId=" + parentId + ", "
          + "postId=" + postId
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof GetPostComment) {
        GetPostComment that = (GetPostComment) o;
        return this.__typename.equals(that.__typename)
         && this._id.equals(that._id)
         && this.createdAt.equals(that.createdAt)
         && this.creatorName.equals(that.creatorName)
         && this.content.equals(that.content)
         && this.likes == that.likes
         && this.dislikes == that.dislikes
         && ((this.parentId == null) ? (that.parentId == null) : this.parentId.equals(that.parentId))
         && this.postId.equals(that.postId);
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= _id.hashCode();
        h *= 1000003;
        h ^= createdAt.hashCode();
        h *= 1000003;
        h ^= creatorName.hashCode();
        h *= 1000003;
        h ^= content.hashCode();
        h *= 1000003;
        h ^= likes;
        h *= 1000003;
        h ^= dislikes;
        h *= 1000003;
        h ^= (parentId == null) ? 0 : parentId.hashCode();
        h *= 1000003;
        h ^= postId.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<GetPostComment> {
      @Override
      public GetPostComment map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final String _id = reader.readString($responseFields[1]);
        final Object createdAt = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[2]);
        final String creatorName = reader.readString($responseFields[3]);
        final String content = reader.readString($responseFields[4]);
        final int likes = reader.readInt($responseFields[5]);
        final int dislikes = reader.readInt($responseFields[6]);
        final String parentId = reader.readString($responseFields[7]);
        final String postId = reader.readString($responseFields[8]);
        return new GetPostComment(__typename, _id, createdAt, creatorName, content, likes, dislikes, parentId, postId);
      }
    }
  }
}
