import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	const [count, setCount] = useState(0);

	function foo() {
		setCount((c) => c + 1);
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="main">
				<button onClick={foo}>X</button>
				<div>{count}</div>
			</div>
		</div>
	);
};

export default Home;
